### ISSUE TITLE
Running ./bin/sbl from the current x64-master.zip file immediately seg faults

### ISSUE THREAD

**Issue by KCaseySW** [spitbol/x64#11]
I'm hoping to get some guidance toward a solution from knowledgeable users.  With the following Linux Mint 20.1 Unix system:
Linux FLEX 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Running ./bin/sbl from the current x64-master.zip file immediately seg faults, like below:
$ strace ./bin/sbl -
execve("./bin/sbl", ["./bin/sbl", "-"], 0x7ffde8d40288 /* 53 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x629af8)       = 0
set_tid_address(0x629b30)               = 15101
dup(0)                                  = 3
close(0)                                = 0
dup(3)                                  = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0), ...}) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0), ...}) = 0
brk(NULL)                               = 0xae5000
brk(0x8ae5000)                          = 0x8ae5000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x62877a} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Comment by CheyenneWills** [comment]
It's failing at the very beginning of 'startup' (it's failing on my system
as well - gentoo: linux kernel -> 5.10.27-gentoo)

I used gdb and traced through main, the call to startup is failing.
Stepping into startup (0x62877a), shows the 1st instruction as the pop
%rax (as per int.asm).
Execution fails  with the 1st instruction in startup.  Looking at the pmap
shows that the memory location is marked as non-executable

   pmap -x -p 8478
   8478:   .../sbl/x64-master/bin/sbl -
   Address           Kbytes     RSS   Dirty Mode  Mapping
   0000000000400000     144     128      12 r-x--
..../sbl/x64-master/bin/sbl
   0000000000623000      28      28      12 rw---
..../sbl/x64-master/bin/sbl
   000000000062a000  131076       4       4 rw---   [ anon ]
   00007ffff7ffa000      16       0       0 r----   [ anon ]
   00007ffff7ffe000       4       4       0 r-x--   [ anon ]
   00007ffffffdd000     136       8       8 rwx--   [ stack ]
   ---------------- ------- ------- -------
   total kB          131404     172      36

Looking at int.asm, it looks like there is a missing segment .text
directive before the executable code.

/Cheyenne

**Comment by CheyenneWills** [comment]
Something has changed "recently" in the Linux kernel (I haven't had a chance to go digging).

On an older kernel (4.18 - Centos7) system the pmap shows that the area has rwx permissions for the 623000 area, on a linux 5.10 system it's showing just rw.

**Comment by CheyenneWills** [comment]
Adding the segment .text does fix the problem

**Comment by KCaseySW** [comment]
Thanks, Cheyenne, for the analysis.  Please clarify the suggested next
steps.
Is the addition put into a re-packaged zip file to be created at a later
time?
Is the existing zip file complete enough for me to add your adjustment to
int.asm, then re-assemble/re-compile all the parts without a working sbl
program?
Thank you in advance.
Kevin

**Comment by CheyenneWills** [comment]
The file bin/sbl will not run on a Linux 5.10 system (nor will an installed version of spitbol)..

I believe the steps to build from the existing .zip file is:

In int.asm add the   segment .text statement before the 'global save_regs' statement (around line 314).
On a pre-linux 5.10 system do a make

You can then simply copy the sbl binary to where you want the executable installed (e.g. /usr/local/bin).

It does look like the makefile is also "broken", the make target "spitbol:" doesn't place the built binary in the bin directory where the "install:" target is looking for it.

**Comment by CheyenneWills** [comment]
See pull request #12 

Note I did not include a rebuilt sbl binary.  I will leave that to the upstream maintainers.

**Comment by KCaseySW** [comment]
Hi, Cheyenne,
Your addition applies and assembles without error.
The challenge is that the make file depends upon a running sbl to generate
all the required files.
Am I missing the method of solving this dependency chain?
Thanks for any thoughts.
Kevin

**Comment by CheyenneWills** [comment]
Yes -- there is a chicken and egg issue.  You need a usable spitbol system in order to bootstrap the build so that it can generate the assembly source to build spitbol.

If you have access to a Linux system with a older kernel, you should be able to generate the required .asm files and go from there.

I think I will add another pull request that supplies the bootstrap asm files.

**Comment by CheyenneWills** [comment]
Left another pull request #13 that adds pre-built sbl.asm and err.asm  to allow bootstrapping the build from scratch.

**Comment by KCaseySW** [comment]
Hi, Chellyenne,
Thank you for preparing the three pull requests.  Using those files and a
bit of adjusting, I was able to run your updated makefile and passed the
sanity tests.
The sbl hello.sbl test ran to completion.
The make bootsbl invocation does produce a number of error messages that
make me wonder about the robustness and completeness of the now-running sbl
program.
Here's the modules reporting warnings.  Perhaps it's just the passage of
time that causes ever-improving compiler syntax checking to find earlier
lack of precision in older code.
Thanks again for your assistance.
Kevin
MODULE PROBLEM-AREA
compress.c exit
dosys.c system
getargs.c exit
main.c main, exit
osclose.c kill
ospipe.c exit
oswait.c wait
prompt.c exit
rdenv.c rdenv
stubs.c zysdm, zystt
swcinp.c exit
sysax.c zysax
sysdc.c zysdc
sysdt.c zysdt
sysej.c exit
sysil.c zysil
sysin.c zysin
sysio.c zysio
sysmm.c exit
syspl.c rearmbrk
sysstdio.c zysrd
systty.c zyspi
wrtaout.c clock, rename

**Comment by CheyenneWills** [comment]
All the messages are associated with picky compiler warnings mostly implicit-function-declaration and  implicit-int for some returns. Nothing to worry about.  They could be cleaned up with some extra includes or adding some prototypes in a few spots.

**Comment by CheyenneWills** [comment]
This should now be resolved in master.

In addition, a commit was pushed that cleaned up the compiler warnings.

**Comment by haijinSk** [comment]
Sir, I do appreciate your effort, but unfortunately, at least in my case, it's still fails/crashes when I run the "sbl" to test it before make/install... I have "non-english", localized Ubuntu, but I think in English it's "Illegal instruction (memory dump saved)".

**Comment by CheyenneWills** [comment]
> Sir, I do appreciate your effort, but unfortunately, at least in my case, it's still fails/crashes when I run the "sbl" to test it before make/install... I have "non-english", localized Ubuntu, but I think in English it's "Illegal instruction (memory dump saved)".

Make sure you are not pointing to an older version of sbl (check your PATH)

**Comment by haijinSk** [comment]
Thank you for your response. When I unzip the master, there is one sbl file and another in the bin directory. Both seems the same "St 29. december 2021, 03∶44∶51" and both fail: "Illegal instruction (memory dump saved), when I try run either. I have no sbl in the PATH (variable), I'm pointing to the sbl files exactly with dot. The "illegal instruction" might in mean that maybe my processor is too old? Yes, I have "Intel Core 2 Duo CPU E6750 @ 2.66GHz × 2". But I have no problem with any modern software I use or other with other programming language installed via make/install compilation, so I don't know. I'm not good at too "low level" computer things.

**Comment by CheyenneWills** [comment]
> Thank you for your response. When I unzip the master, there is one sbl file and another in the bin directory. Both seems the same "St 29. december 2021, 03∶44∶51" and both fail: "Illegal instruction (memory dump saved)", when I try run either. I have no sbl in the PATH (variable), I'm pointing to the sbl files exactly with dot. The "illegal instruction" might in mean that maybe my processor is too old? Yes, I have "Intel Core 2 Duo CPU E6750 @ 2.66GHz × 2". But I have no problem with any modern software I use or with other programming language installed via make/install compilation, so I don't know. I'm not good at too "low level" computer things.

Can you do a cat /proc/cpuinfo?

Also can you try building via the "bootsbl"

make bootsbl
make BASEBOL=bootsbl spitbol

The current makefile might need tweaking to adjust the CFLAGS to specify a more "generic" processor.  Also there might then be issues with the cpu requirements of the code pulled in from the static libraries.

I think the "correct" direction would be to rework the makefile to always build via the "bootsbl" method.  That way there would be no problems with mismatched instruction sets.

**Comment by haijinSk** [comment]
Thank you very much.

1. 
when I run "make bootsbl", I get:

cp bootstrap/sbl.asm .
cp bootstrap/err.asm .
nasm -f elf64 -d m64 err.asm
nasm -f elf64 -d m64 int.asm
nasm -f elf64 -d m64 sbl.asm
gcc -Dm64 -m64 -static  -c osint/*.c
gcc -Dm64 -m64 -static  *.o -obootsbl -lm
rm -f *.o *.lst *.map *.err err.lex sbl.lex sbl.err sbl.asm err.asm

2.
when I run: "make BASEBOL=bootsbl spitbol", I get:
bootsbl lex.sbl 
make: bootsbl: Command not found
make: *** [makefile:41: spitbol] Error 127

3.
And my cpu info, with "cat /proc/cpuinfo", I get:
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 Duo CPU     E6750  @ 2.66GHz
stepping	: 11
microcode	: 0xba
cpu MHz		: 2003.000
cache size	: 4096 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority vpid dtherm
vmx flags	: vnmi flexpriority tsc_offset vtpr vapic
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5333.74
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 Duo CPU     E6750  @ 2.66GHz
stepping	: 11
microcode	: 0xba
cpu MHz		: 2043.124
cache size	: 4096 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority vpid dtherm
vmx flags	: vnmi flexpriority tsc_offset vtpr vapic
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5333.74
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

4.
So, that's it. I've tried, you, sir have tried and I'm afraid, I guess I'm not destined, for now, with my CPU, to use this great version of SNOBOL. At least I think, it's out of my competence to adjust the makefile for my CPU; or I have no idea what exactly to put to the CFLAGS line in the makefile instead of it current content.

Anyway, thank you very much.

**Comment by CheyenneWills** [comment]
My mistake on the make command, try:

make BASEBOL=./bootsbl spitbol

**Comment by haijinSk** [comment]
Sir, you are amazing... Thank you very much!

Yes, "make BASEBOL=./bootsbl spitbol" works!

To summarize my path:

I've ran:
make bootsbl
make BASEBOL=./bootsbl spitbol

That created new sbl file.
I inserted it to the bin folder (replaced the original sbl file)

A test "./bin/sbl test/hello.sbl" worked.

Then I've ran:
make (I don't know if this step was necessary, if the sbl file worked already.)
sudo make install

Now, the sbl file/command/program is in my PATH (there is no spitbol command/program).

And now I can run snobol4 programs, I only found that SNOBOL statements/keywords have to be in lowercase.

And one more now: now I see in the README.md in Required Programs: 
"The command musl-gcc must be used instead of gcc to link to the musl library and include files."
And I have only gcc, and if I'm right, in my case it doesn't matter, because my case has something to do with "statically-linked" sbl file...

Thank you very much! I appreciate your time, energy, patience and talent... Thanks!

**Comment by CheyenneWills** [comment]
I've updated the README.md file and the makefile to be better in sync.  The README file had a lot of references to the executable 'spitbol' within the build directory while the makefile was actually using 'sbl'.  The makefile now installs the executable as '/usr/local/bin/spitbol'

I've also turned on support for -case / &case so that older spitbol programs should work if they are in upper case.

Could you also retry the floating point test?  Make sure you are using the current ./bin/sbl file for that test.

**Comment by haijinSk** [comment]
Thank you! Now:

1. Nice "spitbol" command works/exists.
2. Uppercase programs works.
3. The floating math works.

In my case, I had to do this:
1. make bootsbl
2. make BASEBOL=./bootsbl spitbol (README file says "BOOTBOL" but in my case only "BASEBOL" works)
3. New sbl file was created, and I had to insert it to the bin folder (and replaced the original sbl file from the master).
4. sudo make install
5. And some time ago when I read your conversation with Mr. KCaseySW, I installed NASM assembler.

Sir, thank you very much. Thank you for maintaining, keeping alive this great version/implementation of SNOBOL4. There are many great stars on the sky of programming languages, but discovering SNOBOL's patterns can make a day. It's so old and yet so new and fresh... Sir, thank you (and the original owner of this project) for your effort, your art, science and magic of programming.

**Comment by haijinSk** [comment]
PS: As I'm now playing with this spitbol, I can see (it's something I can easily understand and check) one minor thing in the README:

1. It says "The initial value of &CASE is zero, not one as in prior versions", but in my case, it's one.
2. It says "The initial value of &TERM is one, not null as in prior versions", but in my case there is no "&TERM" variable/keyword. I'm not sure, I'm new to SNOBOL4 but maybe it is typo and it means/should be: &TRIM. And in my case the initial value of &TRIM is 0.

**Comment by CheyenneWills** [comment]
> 
> 1. make bootsbl
>    make BASEBOL=./bootsbl spitbol (README file says "BOOTBOL" but in my case only "BASEBOL" works)
> 2. A new sbl file was created, and I had to insert it to the bin folder (and replaced the original sbl file from the master).
> 3. sudo make install


Yes, there is another typo in the README.md.  It should be make BASEBOL=./bootsbl as well as some additional typos (&TERM should be &TRIM).

I have a commit pending that fixes these typos, but it also "corrects" the &case so that by default case folding is turned off.  I will be adding a new compiler option that will enable case folding so that older programs and be used without changing their source.

**Comment by CheyenneWills** [comment]
I have published a new version, V4.0a which should address these problems.
